-- -------------LISTA DE CONVÊNIOS MÉDICOS ----------------

INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (1, 'Allianz Saúde');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (2, 'Amil');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (3, 'Apas');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (4, 'Assefaz');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (5, 'Assim');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (6, 'Banco Central');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (7, 'Bradesco Saúde');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (8, 'CABESP');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (9, 'Camed');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (10, 'Cassi');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (11, 'Clinipan');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (12, 'Dix-Amico');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (13, 'Eletros-Saúde');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (14, 'Embratel(Pame)');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (15, 'Forluz');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (16, 'Funcef');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (17, 'FunCesp');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (18, 'Gama Saúde');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (19, 'Geap');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (20, 'Golden Cross');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (21, 'Hapvida');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (22, 'Intermédica');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (23, 'IPE-Saúde');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (24, 'Itaú Seguros');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (25, 'Lincx');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (26, 'Medial Saúde');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (27, 'Mediservice');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (28, 'Nossa Saúde');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (29, 'Notre Dame');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (30, 'Omint');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (31, 'Panamed Saúde');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (32, 'Petrobras');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (33, 'Porto Seguro');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (34, 'Postal Saúde');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (35, 'Qualicorp');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (36, 'SAMP');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (37, 'Saude Caixa');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (38, 'Sinam');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (39, 'Sul América Saúde');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (40, 'Transmontano');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (41, 'Unibanco Saúde');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (42, 'Unimed');
INSERT INTO `digital_care`.`convenio` (`id`,`nome`) VALUES (43, 'Yasuda Marítima');
