INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Alergologia‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Anatomia patológica‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Andrologia‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Anestesiologia‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Angiologia‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Cancerologia‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Cardiologia');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Clínica médica‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Dermatologia‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Endocrinologia‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Epidemiologia');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Medicina esportiva‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Gastroenterologia');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Geriatria‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Gerontologia‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Ginecologia');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Hematologia‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Hepatologia');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Imunologia‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Infectologia');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Mastologia');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Medicina de emergência‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Medicina de família e comunidade‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Medicina de transplantes‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Medicina do trabalho‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Medicina intensiva‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Medicina legal‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Medicina nuclear');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Medicina tropical‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Nefrologia‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Neonatologia‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Neurologia‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Obstetrícia‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Oftalmologia');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Oncologia‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Ortopedia‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Otorrinolaringologia‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Patologia clínica‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Pediatria‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Pneumologia‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Podologia‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Psiquiatria‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Radiologia');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Reabilitação‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Reumatologia');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Medicina do sono‎');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Traumatologia');
INSERT INTO `digital_care`.`especialidade` (`nome`) VALUES ('Urologia‎');